print("Welcome to my daily routine!")
print("I wake up at 9:00 A.M")
print("I eat breakfast do some of my homework.")
print("I do some of my chores.")
print("I play indoors for a while.")
print("I go downstairs and eat lunch.")
print("I study for a while.")
print("I go to my room to attend my coding class.")
print("I go to friends house to play games but sometime go to the park to play football.")
print("I sit with my family and talk a while.")
print("I eat food and then sometimes watch a movie.")
print("I go to sleep.")